### ISSUE TITLE
Remove Nomics and replace chart 

### ISSUE THREAD

**Issue by CharlVS** [KomodoPlatform/atomicdex-mobile#10]
![image](https://user-images.githubusercontent.com/77973576/230581867-2e552bb7-e6d2-4c9e-9018-2facba825264.png)

**Comment by ologunB** [comment]
`nomics_id` isnt used anywhere in the app. And by replacing the chart, how do you mean? @CharlVS

**Comment by CharlVS** [comment]
@ologunB I've copied the issue verbatim from the desktop project. Was referring more generally to updating the coins config and update/remove any references.

**Comment by ologunB** [comment]
> @ologunB I've copied the issue verbatim from the desktop project. Was referring more generally to updating the coins config and update/remove any references.

Oh, I saw the issue yesterday but it doesn't apply to mobile. You can close the issue in respect to that. The present #9 uses the latest config, so might not need another update.
