### ISSUE TITLE
mm2_main erorr, undefined reference

### ISSUE THREAD

**Issue by ingego** [KomodoPlatform/atomicdex-mobile#11]
![image](https://user-images.githubusercontent.com/26673298/230855749-668a6ccc-9449-4a12-b89a-54d3bd97348d.png)
![image](https://user-images.githubusercontent.com/26673298/230855774-2e1f985f-36ff-451e-8b76-7164beaf9094.png)

**Comment by CharlVS** [comment]
@ingego If you downloaded the builds from the last link I sent, please update to the builds in the link below:

https://drive.proton.me/urls/W2J2AC3KNC#LXPkBBGleN7M
