### ISSUE TITLE
Mobile application is not built on versions 14+ Xcode

### ISSUE THREAD

**Issue by ExpoinDEX** [KomodoPlatform/atomicdex-mobile#24]
The app is mobile and the DEX API library is successfully built on versions 13+ Xcode 
— But the mobile application and the library do not pass the build on Xcode 14+ versions and the build falls with the loss of dependencies of the main functions of the library. This does not allow it to be uploaded to the app store. Help solve the problem

**Comment by ExpoinDEX** [comment]
It turns out that it is impossible to add an assembly on 13 x code to testflight. Therefore, what is in the build at the moment is not suitable for iOS devices. This is very frustrating, since we are already starting a marketing campaign to promote the product, but there is no mobile application for iOS

**Comment by smk762** [comment]
Please add any error message output here so we can attempt to identify potential resolutions.

**Comment by ExpoinDEX** [comment]
> Please add any error message output here so we can attempt to identify potential resolutions.


![photo_2023-05-18_23-45-00](https://github.com/KomodoPlatform/atomicdex-mobile/assets/128407432/7e5baa29-e8e8-4983-9c29-b0dd96878916)
We did everything in accordance with the documentation, but the errors are still the same as in the screenshot.

Application version: v0.6.2
DEX API version: v1.0.3

**Comment by CharlVS** [comment]
@ExpoinDEX Is the code for your project public?

**Comment by CharlVS** [comment]
@ExpoinDEX Please do the following command and share the output:

```bash
flutter doctor --verbose
```

**Comment by ExpoinDEX** [comment]
[✓] Flutter (Channel stable, 3.7.10, on macOS 12.6 21G115 darwin-arm64, locale en-RU)
    • Flutter version 3.7.10 on channel stable at /Users/anis/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (8 weeks ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/anis/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/anis/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.71.1)
    • VS Code at /Users/anis/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • EE89748D-6C6E-4313-B2F8-DB270360208A • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS
      12.6 21G115 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google
      Chrome 114.0.5735.90

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by CharlVS** [comment]
>Flutter version 3.7.10

@ExpoinDEX Is this the Flutter SDK you area using to build the app? Please make sure you're using Flutter 2.8.1.

**Comment by CharlVS** [comment]
No response was received from the issue author, and provided information is inconsistent. Feel free to re-open with more info or with the source code shared.
